[server]
enableStaticServing = true

[theme]
primaryColor = "#0071e3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#1d1d1f"
linkColor = "#0066cc"
borderColor = "#d2d2d7"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "12px"
font = "SF Pro Display"
codeFont = "SF Mono"
codeBackgroundColor = "#fbfbfd"

[theme.sidebar]
backgroundColor = "#f5f5f7"
secondaryBackgroundColor = "#f5f5f7"


[[theme.fontFaces]]
url = "app/static/sf-mono/SFMonoRegular.otf"
family = "SF Mono"
weight = 400

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Black.otf"
family = "SF Pro Display"
weight = 900

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Bold.otf"
family = "SF Pro Display"
weight = 700

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Heavy.otf"
family = "SF Pro Display"
weight = 800

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Light.otf"
family = "SF Pro Display"
weight = 300

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Medium.otf"
family = "SF Pro Display"
weight = 500

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Regular.otf"
family = "SF Pro Display"
weight = 400

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Semibold.otf"
family = "SF Pro Display"
weight = 600

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Thin.otf"
family = "SF Pro Display"
weight = 100

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Ultralight.otf"
family = "SF Pro Display"
weight = 200
